# Generated by Django 2.1.7 on 2019-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companyID', models.CharField(max_length=100)),
                ('logoURL', models.CharField(max_length=100)),
                ('requestURL', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
                ('handler', models.CharField(max_length=100)),
            ],
        ),
    ]
